import "./globals.css";
import { Poppins } from "@next/font/google";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  // configuración para tailwind abajo
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <nav>
          <h1>logo</h1>
          <ul>
            <li>list </li>
            <li>list</li>
            <li>lsit</li>
          </ul>
        </nav>
        {/* children es la renderización de las diferentes vistas de la
página */}
        {children}
      </body>
    </html>
  );
}
